{% set name = "sagemaker-code-editor" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  # github repo set-up is in progress, once ready we will use the github release url here instead of the s3 url
  url: https://sagemaker-code-editor-1696292125.s3.us-west-2.amazonaws.com/code-editor1.2.0.tar.gz
  sha256: 26304296e0815e87c70ff32df0bf6fae48d26d4a5ce31dc39336d443c00033b0
  folder: sagemaker-code-editor

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    # dependencies needed for open source microsoft/vscode - https://github.com/microsoft/vscode/wiki/How-to-Contribute 
    # updating nodejs to >=20.0 as it's requirement for vscode - https://github.com/microsoft/vscode/wiki/How-to-Contribute
    - nodejs >=20.0
    - yarn <2
    - make
    - pkg-config
    - compilers
    - sysroot_linux-64 ==2.17
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - krb5
    
    # jq  - used to parse ripgrep version number
    - jq
    # node-gyp is broken with python 3.12 - https://github.com/nodejs/node-gyp/issues/2869, so pulling in distutils via setuptools
    - setuptools
  host:
    # dependencies needed for open source microsoft/vscode - https://github.com/microsoft/vscode/wiki/How-to-Contribute 
    - nodejs >=20.0
    - libxkbfile
    - xorg-libx11
    - krb5
    - libsecret

    # we're using conda ripgrep instead of the node module - refer to build.sh
    - ripgrep
  run:
    - ripgrep

test:
  commands:
    - sagemaker-code-editor --help
    # we're using conda ripgrep instead of the node module so testing it's functionality
    - ${PREFIX}/share/sagemaker-code-editor/node_modules/@vscode/ripgrep/bin/rg --help

about:
  home: https://aws.amazon.com/sagemaker/
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - LICENSE.vscode.txt
    - LICENSE-THIRD-PARTY
    - ThirdPartyNotices.vscode.txt
  summary: Code Editor based on Code-OSS, Visual Studio Code Open Source

extra:
  recipe-maintainers:
    - aws-prayags
    - arkaprava08
    - aws-pangestu
    - navinsoni
    - sgganjo
