{% set name = "sagemaker-code-editor" %}
{% set version = "1.1.5dev0" %}


package:
  name: {{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:

  url: https://github.com/aws/sagemaker-code-editor/releases/download/v1.1.5dev0/code-editorv1.1.5dev0.tar.gz
  sha256: 08df98934fcb4db0e3ae6cc91ac9b857bafd113009e97babbbd7ace7afd50f7e
  folder: sagemaker-code-editor

build:
  number: 3
  skip: true  # [not linux]

requirements:
  build:
    # dependencies needed for open source microsoft/vscode - https://github.com/microsoft/vscode/wiki/How-to-Contribute 
    # updating nodejs to >=20.0 as it's requirement for vscode - https://github.com/microsoft/vscode/wiki/How-to-Contribute
    # vscode has dependency on @azure/msal-node@2.5 which expects node version 20
    - nodejs >=20.0,<21
    - yarn <2
    - make
    - pkg-config
    - compilers
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - krb5
    
    # jq  - used to parse ripgrep version number
    - jq
    # node-gyp is broken with python 3.12 - https://github.com/nodejs/node-gyp/issues/2869, so pulling in distutils via setuptools
    - setuptools
  host:
    # dependencies needed for open source microsoft/vscode - https://github.com/microsoft/vscode/wiki/How-to-Contribute 
    - nodejs >=20.0,<21
    - libxkbfile
    - xorg-libx11
    - krb5
    - glib
    - libsecret
    - xorg-xproto
    - xorg-kbproto

    # we're using conda ripgrep instead of the node module - refer to build.sh
    - ripgrep
  run:
    - ripgrep

test:
  commands:
    - sagemaker-code-editor --help
    # we're using conda ripgrep instead of the node module so testing it's functionality
    - ${PREFIX}/share/sagemaker-code-editor/node_modules/@vscode/ripgrep/bin/rg --help

about:
  home: https://aws.amazon.com/sagemaker/
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - LICENSE.vscode.txt
    - LICENSE-THIRD-PARTY
    - ThirdPartyNotices.vscode.txt
  summary: Code Editor based on Code-OSS, Visual Studio Code Open Source

extra:
  recipe-maintainers:
    - aws-prayags
    - arkaprava08
    - aws-pangestu
    - navinsoni
    - sgganjo
    - aws-asolidu
    - goel-akas
    - zuoyuanh
    - sthodimi
    - aws-zamesjhu
