github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
azure:
    settings_linux:
        swapfile_size: 10GiB
    # linux image before running the Docker container for building
    free_disk_space: False
